title:  # The title of the blog
author: Vipul Vaibhaw # Your name
email: vaibhaw.vipul@gmail.com # your email shown in the footer
url: https://vaibhawvipul.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  My long form writing about tech and other things.
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://yt3.googleusercontent.com/kdaIkpMZJztcZryW3g5H6sH9Fd6WjVsbjwukTMlmoDzF1HHVJ6BpGzENUTfIyRKSH8KRV2OhAg=s900-c-k-c0x00ffffff-no-rj" # avatar in about page
  about_you: Software Engineer and Math guy. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: vaibhaw_vipul
    github: vaibhawvipul
    rss: RSS
    # dribbble:
    facebook:
    # flickr:
    # instagram:
    # linkedin:
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
# theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
